export const themes = {
  dia: { bg: 'radial-gradient(1100px 680px at 78% -8%, rgba(97,195,217,.30), transparent 60%), radial-gradient(900px 560px at 6% 108%, rgba(253,217,183,.55), transparent 58%), #f0eee6', ink:'#22383f', soft:'#5a6a6d', faint:'#8b9698', accent:'#ee7067', accentSoft:'rgba(238,112,103,.16)', line:'#dcd8c9', card:'#fffdf8', border:'#e6e2d4', glow:'rgba(97,195,217,.5)', bloom:'rgba(238,112,103,.22)', person:'#2c5560', rim:'rgba(255,255,255,.7)', shade:'rgba(120,150,160,.28)', shadow:'rgba(80,110,120,.22)' },
  calor: { bg: 'radial-gradient(1000px 640px at 82% -6%, rgba(252,215,105,.55), transparent 58%), radial-gradient(900px 560px at 4% 106%, rgba(238,112,103,.38), transparent 56%), #fbf2e6', ink:'#4a2a22', soft:'#7a5448', faint:'#a98a7c', accent:'#e0584d', accentSoft:'rgba(224,88,77,.16)', line:'#ecd9c4', card:'#fffaf2', border:'#f0dcc6', glow:'rgba(252,215,105,.6)', bloom:'rgba(238,112,103,.26)', person:'#6e3a2c', rim:'rgba(255,255,255,.72)', shade:'rgba(180,120,80,.26)', shadow:'rgba(150,90,50,.2)' },
  frio: { bg: 'radial-gradient(1000px 640px at 80% -8%, rgba(97,195,217,.42), transparent 58%), radial-gradient(900px 560px at 4% 108%, rgba(255,255,255,.85), transparent 56%), #eaf1f3', ink:'#1c3b44', soft:'#4f6970', faint:'#85999e', accent:'#0081a8', accentSoft:'rgba(0,129,168,.14)', line:'#d3e0e3', card:'#fbfdfe', border:'#dde9eb', glow:'rgba(97,195,217,.55)', bloom:'rgba(97,195,217,.28)', person:'#1e4b58', rim:'rgba(255,255,255,.85)', shade:'rgba(90,140,155,.26)', shadow:'rgba(60,110,125,.2)' },
  madrugada: { bg:'radial-gradient(820px 620px at 76% 14%, rgba(252,215,105,.18), transparent 56%), radial-gradient(700px 540px at 70% 8%, rgba(238,112,103,.10), transparent 60%), #15151b', ink:'#ece4d7', soft:'#a59c8e', faint:'#6f6a62', accent:'#f0c24f', accentSoft:'rgba(240,194,79,.16)', line:'rgba(255,255,255,.10)', card:'rgba(255,255,255,.045)', border:'rgba(255,255,255,.10)', glow:'rgba(252,215,105,.32)', bloom:'rgba(240,194,79,.10)', person:'#f0c24f', rim:'rgba(255,240,210,.5)', shade:'rgba(0,0,0,.4)', shadow:'rgba(0,0,0,.5)' },
  'noche-calor': { bg:'radial-gradient(840px 640px at 74% 12%, rgba(238,112,103,.22), transparent 56%), radial-gradient(680px 520px at 72% 6%, rgba(252,215,105,.14), transparent 60%), #1a1418', ink:'#f0e5db', soft:'#ad9d92', faint:'#776861', accent:'#f08a72', accentSoft:'rgba(240,138,114,.18)', line:'rgba(255,255,255,.10)', card:'rgba(255,255,255,.05)', border:'rgba(255,255,255,.11)', glow:'rgba(238,112,103,.34)', bloom:'rgba(240,138,114,.12)', person:'#f08a72', rim:'rgba(255,225,205,.5)', shade:'rgba(0,0,0,.42)', shadow:'rgba(0,0,0,.5)' }
}

export const copies = {
  dia: ['Buenos días','Tu vida es más grande que ','la comezón',' de la urticaria.','Entender qué te pasa es el primer paso para que ocupe menos espacio. Te acompañamos a llegar lista a tu próxima consulta.','Descúbrelo en 1 minuto','Un autochequeo que te orienta. No reemplaza a tu médico.'],
  calor: ['En Mérida, ahora mismo','En Mérida el calor está fuerte. Y el calor puede subir ','los brotes','.','No es tu imaginación: el calor y la humedad despiertan la piel. Esto puede ayudarte hoy a entender qué te pasa.','Esto puede ayudarte hoy','Un autochequeo que te orienta. No reemplaza a tu médico.'],
  frio: ['Con el frío de esta temporada','Con el frío, a algunas personas la piel se les ','brota','.','Sí, existe la urticaria por frío, y el aire seco del invierno irrita la piel. Esto ayuda a entender qué te pasa.','Entiende qué te pasa','Un autochequeo que te orienta. No reemplaza a tu médico.'],
  madrugada: ['Son las 3:15 a.m.','¿No puedes ','dormir','?','La comezón aparece justo cuando todo se queda en silencio. Respira: no estás sola, y esto pasa. Quédate, te acompañamos.','Quédate un momento','Sin prisa. Cuando amanezca, esto puede ayudarte a entender qué pasa.'],
  'noche-calor': ['Son las 9:00 p.m.','La noche está calurosa, y la comezón no te deja ','dormir','.','El calor de esta noche aviva la piel. Respira: no estás sola, y esto pasa. Quédate, te acompañamos.','Quédate un momento','Sin prisa. Cuando amanezca, esto puede ayudarte a entender qué pasa.']
}

export const questions = {
 p1:['single','¿Qué se parece más a lo que tienes?','Elige la opción más cercana. Puede pasar en cualquier tono de piel.',[['habones','Ronchas o habones que aparecen y se van','Como piquetes de mosco que cambian de lugar'],['hinchazon','Hinchazón de labios, párpados o manos','La piel se infla, más que marcarse'],['solo_comezon','Solo comezón, sin marca visible','Pica, pero no se ve nada en la piel'],['manchas_fijas','Manchas que no se mueven ni desaparecen','Se quedan en el mismo sitio varios días']]],
 p1b:['single','¿La hinchazón es en labios, lengua o garganta, o te cuesta respirar?','Esto es importante: ayuda a descartar una urgencia.',[['urgente','Sí — labios, lengua, garganta, o me cuesta respirar',''],['no_urgente','No — es en párpados, manos o pies','']]],
 p2:['single','¿Las ronchas aparecen, se van y cambian de lugar en menos de un día?','Es el rasgo más característico de la urticaria.',[['si','Sí, salen y desaparecen en horas','Y suelen cambiar de lugar'],['persisten','No, se quedan días en el mismo sitio','O dejan moretón / marca al irse'],['no_seguro','No estoy segura','No me he fijado bien']]],
 p3:['single','¿Cuánto llevas con esto?','Las 6 semanas son la línea entre lo agudo y lo crónico.',[['aguda','Menos de 6 semanas','Empezó hace poco'],['cronica','Más de 6 semanas','Llevo bastante tiempo así'],['no_seguro','No estoy segura','Va y viene desde hace tiempo']]],
 n1:['single','¿Esto empezó mientras dormías, o lo venías sintiendo desde el día?','Nos ayuda a entender tu brote nocturno.',[['empezo_dormido','Empezó o me despertó de noche',''],['venia_del_dia','Ya lo sentía desde el día','']]],
 n2:['single','¿Es la primera noche que te pasa, o ya van varias?','',[['primera','Es la primera vez',''],['varias','Ya van varias noches','']]],
 p4:['single','¿Le encuentras un porqué?','Que no haya causa clara también es una pista valiosa.',[['detonante_claro','Sí, un detonante claro','Una comida, un medicamento, una picadura'],['estreno_nuevo','Estrené algo nuevo hace poco','Cosmético, bloqueador, ropa, detergente'],['sin_patron','No encuentro ningún patrón','Aparece sin razón aparente'],['intermitente','A veces sí, a veces no','No logro identificar qué la dispara']]],
 c1:['single','¿Estrenaste algo en la piel hace poco?','Bloqueador, crema, cosmético o ropa nueva.',[['si','Sí, algo nuevo en la piel',''],['no','No, nada nuevo','']]], c2:['single','¿Las ronchas salen más con el calor, el sudor o el sol?','',[['si','Sí, con calor, sudor o sol',''],['no','No noto esa relación','']]],
 f1:['single','¿Las ronchas aparecen cuando te expones al frío?','Aire frío, agua fría, o al destaparte.',[['si','Sí, con el frío',''],['no','No noto esa relación','']]], f2:['single','¿Tu piel se irrita más con el ambiente seco del invierno?','',[['si','Sí, se reseca e irrita',''],['no','No particularmente','']]],
 p5:['multi','¿Cómo te afecta de verdad?','Marca todo lo que aplique. Esto es justo lo que tu médico necesita saber.',[['sueno','Me quita el sueño',''],['concentracion','Me cuesta concentrarme',''],['evito_planes','Evito salir o hacer planes',''],['angustia','Me angustia o me estresa',''],['trabajo','Afecta mi trabajo','']]],
 p6:['single','¿Ya probaste antihistamínicos y sigues igual?','Los que se venden para la alergia o la comezón.',[['fallido','Sí, los tomé y sigo con síntomas',''],['funciona','Sí, y me ayudaron',''],['ninguno','No he tomado nada',''],['no_sabe','No sé qué tomé','']]]
}
